services:
  go-dns:
    container_name: go-dns
    image: magpiemonitor/dns
    build:
      context: .
      dockerfile: Dockerfile.dns
    ports:
      - "53:53/udp"
    develop:
      watch:
        - action: rebuild
          path: ./internal
          target: /src
        - action: rebuild
          path: ./pkg
          target: /src
    depends_on:
      - postgres

  go-dns-management:
    container_name: go-dns-management
    image: magpiemonitor/dns-management
    build:
      context: .
      dockerfile: Dockerfile.management
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    develop:
      watch:
        - action: rebuild
          path: ./internal
          target: /src
        - action: rebuild
          path: ./pkg
          target: /src
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
